package edu.cn.pojo;

import java.util.Date;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_address.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_address.contact
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_address.addressDesc
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String addressDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_address.postCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_address.tel
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_address.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_address.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_address.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_address.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_address.userId
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_address.id
     *
     * @return the value of smbms_address.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_address.id
     *
     * @param id the value for smbms_address.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_address.contact
     *
     * @return the value of smbms_address.contact
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_address.contact
     *
     * @param contact the value for smbms_address.contact
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_address.addressDesc
     *
     * @return the value of smbms_address.addressDesc
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getAddressDesc() {
        return addressDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_address.addressDesc
     *
     * @param addressDesc the value for smbms_address.addressDesc
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setAddressDesc(String addressDesc) {
        this.addressDesc = addressDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_address.postCode
     *
     * @return the value of smbms_address.postCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_address.postCode
     *
     * @param postCode the value for smbms_address.postCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_address.tel
     *
     * @return the value of smbms_address.tel
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_address.tel
     *
     * @param tel the value for smbms_address.tel
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_address.createdBy
     *
     * @return the value of smbms_address.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_address.createdBy
     *
     * @param createdBy the value for smbms_address.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_address.creationDate
     *
     * @return the value of smbms_address.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_address.creationDate
     *
     * @param creationDate the value for smbms_address.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_address.modifyBy
     *
     * @return the value of smbms_address.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_address.modifyBy
     *
     * @param modifyBy the value for smbms_address.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setModifyBy(Long modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_address.modifyDate
     *
     * @return the value of smbms_address.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_address.modifyDate
     *
     * @param modifyDate the value for smbms_address.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_address.userId
     *
     * @return the value of smbms_address.userId
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_address.userId
     *
     * @param userId the value for smbms_address.userId
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}