package edu.cn.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Bill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.billCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String billCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.productName
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.productDesc
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.productUnit
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String productUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.productCount
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private BigDecimal productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.totalPrice
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.isPayment
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Integer isPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_bill.providerId
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long providerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.id
     *
     * @return the value of smbms_bill.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.id
     *
     * @param id the value for smbms_bill.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.billCode
     *
     * @return the value of smbms_bill.billCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getBillCode() {
        return billCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.billCode
     *
     * @param billCode the value for smbms_bill.billCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setBillCode(String billCode) {
        this.billCode = billCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.productName
     *
     * @return the value of smbms_bill.productName
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.productName
     *
     * @param productName the value for smbms_bill.productName
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.productDesc
     *
     * @return the value of smbms_bill.productDesc
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.productDesc
     *
     * @param productDesc the value for smbms_bill.productDesc
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.productUnit
     *
     * @return the value of smbms_bill.productUnit
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getProductUnit() {
        return productUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.productUnit
     *
     * @param productUnit the value for smbms_bill.productUnit
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProductUnit(String productUnit) {
        this.productUnit = productUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.productCount
     *
     * @return the value of smbms_bill.productCount
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public BigDecimal getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.productCount
     *
     * @param productCount the value for smbms_bill.productCount
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProductCount(BigDecimal productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.totalPrice
     *
     * @return the value of smbms_bill.totalPrice
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.totalPrice
     *
     * @param totalPrice the value for smbms_bill.totalPrice
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.isPayment
     *
     * @return the value of smbms_bill.isPayment
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Integer getIsPayment() {
        return isPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.isPayment
     *
     * @param isPayment the value for smbms_bill.isPayment
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setIsPayment(Integer isPayment) {
        this.isPayment = isPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.createdBy
     *
     * @return the value of smbms_bill.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.createdBy
     *
     * @param createdBy the value for smbms_bill.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.creationDate
     *
     * @return the value of smbms_bill.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.creationDate
     *
     * @param creationDate the value for smbms_bill.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.modifyBy
     *
     * @return the value of smbms_bill.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.modifyBy
     *
     * @param modifyBy the value for smbms_bill.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setModifyBy(Long modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.modifyDate
     *
     * @return the value of smbms_bill.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.modifyDate
     *
     * @param modifyDate the value for smbms_bill.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_bill.providerId
     *
     * @return the value of smbms_bill.providerId
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_bill.providerId
     *
     * @param providerId the value for smbms_bill.providerId
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }
}