package edu.cn.pojo;

import java.util.Date;

public class Provider {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String proCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proName
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proDesc
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String proDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proContact
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String proContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proPhone
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String proPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proAddress
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String proAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.proFax
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String proFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_provider.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long modifyBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.id
     *
     * @return the value of smbms_provider.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.id
     *
     * @param id the value for smbms_provider.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proCode
     *
     * @return the value of smbms_provider.proCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getProCode() {
        return proCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proCode
     *
     * @param proCode the value for smbms_provider.proCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProCode(String proCode) {
        this.proCode = proCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proName
     *
     * @return the value of smbms_provider.proName
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proName
     *
     * @param proName the value for smbms_provider.proName
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proDesc
     *
     * @return the value of smbms_provider.proDesc
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getProDesc() {
        return proDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proDesc
     *
     * @param proDesc the value for smbms_provider.proDesc
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProDesc(String proDesc) {
        this.proDesc = proDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proContact
     *
     * @return the value of smbms_provider.proContact
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getProContact() {
        return proContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proContact
     *
     * @param proContact the value for smbms_provider.proContact
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProContact(String proContact) {
        this.proContact = proContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proPhone
     *
     * @return the value of smbms_provider.proPhone
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getProPhone() {
        return proPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proPhone
     *
     * @param proPhone the value for smbms_provider.proPhone
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProPhone(String proPhone) {
        this.proPhone = proPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proAddress
     *
     * @return the value of smbms_provider.proAddress
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getProAddress() {
        return proAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proAddress
     *
     * @param proAddress the value for smbms_provider.proAddress
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProAddress(String proAddress) {
        this.proAddress = proAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.proFax
     *
     * @return the value of smbms_provider.proFax
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getProFax() {
        return proFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.proFax
     *
     * @param proFax the value for smbms_provider.proFax
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setProFax(String proFax) {
        this.proFax = proFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.createdBy
     *
     * @return the value of smbms_provider.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.createdBy
     *
     * @param createdBy the value for smbms_provider.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.creationDate
     *
     * @return the value of smbms_provider.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.creationDate
     *
     * @param creationDate the value for smbms_provider.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.modifyDate
     *
     * @return the value of smbms_provider.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.modifyDate
     *
     * @param modifyDate the value for smbms_provider.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_provider.modifyBy
     *
     * @return the value of smbms_provider.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_provider.modifyBy
     *
     * @param modifyBy the value for smbms_provider.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setModifyBy(Long modifyBy) {
        this.modifyBy = modifyBy;
    }
}