package edu.cn.pojo;

import java.util.Date;

public class UserDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.userCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.userName
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.userPassword
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.gender
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.birthday
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.phone
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.address
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.userRole
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Long modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.idPicPath
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    private String idPicPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.id
     *
     * @return the value of smbms_user.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.id
     *
     * @param id the value for smbms_user.id
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.userCode
     *
     * @return the value of smbms_user.userCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.userCode
     *
     * @param userCode the value for smbms_user.userCode
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.userName
     *
     * @return the value of smbms_user.userName
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.userName
     *
     * @param userName the value for smbms_user.userName
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.userPassword
     *
     * @return the value of smbms_user.userPassword
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.userPassword
     *
     * @param userPassword the value for smbms_user.userPassword
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.gender
     *
     * @return the value of smbms_user.gender
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.gender
     *
     * @param gender the value for smbms_user.gender
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.birthday
     *
     * @return the value of smbms_user.birthday
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.birthday
     *
     * @param birthday the value for smbms_user.birthday
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.phone
     *
     * @return the value of smbms_user.phone
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.phone
     *
     * @param phone the value for smbms_user.phone
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.address
     *
     * @return the value of smbms_user.address
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.address
     *
     * @param address the value for smbms_user.address
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.userRole
     *
     * @return the value of smbms_user.userRole
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.userRole
     *
     * @param userRole the value for smbms_user.userRole
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setUserRole(Long userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.createdBy
     *
     * @return the value of smbms_user.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.createdBy
     *
     * @param createdBy the value for smbms_user.createdBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.creationDate
     *
     * @return the value of smbms_user.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.creationDate
     *
     * @param creationDate the value for smbms_user.creationDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.modifyBy
     *
     * @return the value of smbms_user.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Long getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.modifyBy
     *
     * @param modifyBy the value for smbms_user.modifyBy
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setModifyBy(Long modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.modifyDate
     *
     * @return the value of smbms_user.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.modifyDate
     *
     * @param modifyDate the value for smbms_user.modifyDate
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.idPicPath
     *
     * @return the value of smbms_user.idPicPath
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public String getIdPicPath() {
        return idPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.idPicPath
     *
     * @param idPicPath the value for smbms_user.idPicPath
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    public void setIdPicPath(String idPicPath) {
        this.idPicPath = idPicPath;
    }




    private int age;

    private String userRoleName;

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getUserRoleName() {
        return userRoleName;
    }

    public void setUserRoleName(String userRoleName) {
        this.userRoleName = userRoleName;
    }

    @Override
    public String toString() {
        return "UserDTO{" +
                "id=" + id +
                ", userCode='" + userCode + '\'' +
                ", userName='" + userName + '\'' +
                ", userPassword='" + userPassword + '\'' +
                ", gender=" + gender +
                ", birthday=" + birthday +
                ", phone='" + phone + '\'' +
                ", address='" + address + '\'' +
                ", userRole=" + userRole +
                ", createdBy=" + createdBy +
                ", creationDate=" + creationDate +
                ", modifyBy=" + modifyBy +
                ", modifyDate=" + modifyDate +
                ", idPicPath='" + idPicPath + '\'' +
                ", age=" + age +
                ", userRoleName='" + userRoleName + '\'' +
                '}';
    }
}