package edu.cn.dao;

import edu.cn.pojo.Address;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    Address selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int updateByPrimaryKey(Address record);
}