package edu.cn.dao;

import edu.cn.pojo.Bill;

public interface BillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int insert(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int insertSelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    Bill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int updateByPrimaryKeySelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_bill
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int updateByPrimaryKey(Bill record);
}