package edu.cn.dao;

import edu.cn.pojo.Provider;

public interface ProviderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int insert(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int insertSelective(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    Provider selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int updateByPrimaryKeySelective(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_provider
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int updateByPrimaryKey(Provider record);
}