package edu.cn.dao;

import edu.cn.pojo.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int updateByPrimaryKey(Role record);
}