package edu.cn.dao;

import edu.cn.pojo.User;
import edu.cn.pojo.UserDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_user
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_user
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_user
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_user
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_user
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_user
     *
     * @mbg.generated Tue Sep 10 09:53:53 CST 2019
     */
    int updateByPrimaryKey(User record);

    User selectUserByUserCodeAndUserPassword(@Param("userCode") String userCode, @Param("userPassword") String userPassword);

    List<UserDTO> selectAllUser();

    UserDTO selectUserById(Long id);
}